# K-Nearest Neighbors Algorithm :- K-Nearest Neighbors (KNN) is a non-parametric, instance-based learning algorithm used for classification and regression.

In [262]:
import pandas as pd 
import seaborn as sns
import numpy as np 
import matplotlib.pyplot as plt

In [263]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [264]:
df = df[['survived','pclass','sex','age','fare','embarked']]
df.head()

   survived  pclass     sex   age     fare embarked
0         0       3    male  22.0   7.2500        S
1         1       1  female  38.0  71.2833        C
2         1       3  female  26.0   7.9250        S
3         1       1  female  35.0  53.1000        S
4         0       3    male  35.0   8.0500        S

In [265]:
df.isnull().sum()

survived      0
pclass        0
sex           0
age         177
fare          0
embarked      2
dtype: int64

In [266]:
df.shape

(891, 6)

In [267]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [268]:
age_imputer = SimpleImputer(strategy='mean')
df['age'] = age_imputer.fit_transform(df[['age']])
embarked_imputer = SimpleImputer(strategy='most_frequent')
df['embarked'] = embarked_imputer.fit_transform(df[['embarked']])[:,0]

In [269]:
df.dropna(inplace = True)
df.isnull().sum()

survived    0
pclass      0
sex         0
age         0
fare        0
embarked    0
dtype: int64

In [270]:
df.shape

(891, 6)

In [271]:
from sklearn.preprocessing import LabelEncoder,StandardScaler
le = LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df['embarked'])

In [272]:
X = df.drop(columns = ['survived'])
Y = df['survived']

In [273]:
sc = StandardScaler()
X_scaled = sc.fit_transform(X)

In [274]:
X_train,X_test,Y_train,Y_test = train_test_split(X_scaled,Y,test_size = 0.2,random_state = 42)

In [275]:
X_train.shape,X_test.shape

((712, 5), (179, 5))

In [276]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors = 7)
clf.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=7)

In [277]:
clf.score(X_test,Y_test)

0.8100558659217877

In [278]:
Y_pred = clf.predict(X_test)

In [279]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.84      0.83      0.84       105
           1       0.76      0.78      0.77        74

    accuracy                           0.81       179
   macro avg       0.80      0.81      0.80       179
weighted avg       0.81      0.81      0.81       179

In [280]:
df = pd.read_csv('Salary_Data.csv')
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [281]:
df.isnull().sum()

Age                    2
Gender                 2
Education Level        3
Job Title              2
Years of Experience    3
Salary                 5
dtype: int64

In [282]:
df = df.dropna()

In [283]:
df['Education Level'].unique()

array(["Bachelor's", "Master's", 'PhD', "Bachelor's Degree",
       "Master's Degree", 'High School', 'phD'], dtype=object)

In [284]:
df['Education Level'] = df['Education Level'].map({"Bachelor's Degree":"Bachelor's","Master's Degree":"Master's", 'phD':'PhD', "Bachelor's":"Bachelor's", "Master's":"Master's", 'PhD':'PhD', 'High School':'High School'})

C:\Users\Asus\AppData\Local\Temp\ipykernel_3548\1683015668.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Education Level'] = df['Education Level'].map({"Bachelor's Degree":"Bachelor's","Master's Degree":"Master's", 'phD':'PhD', "Bachelor's":"Bachelor's", "Master's":"Master's", 'PhD':'PhD', 'High School':'High School'})

In [285]:
freq = df['Job Title'].value_counts().to_dict()
df['Job Title'] = df['Job Title'].map(freq)
df

C:\Users\Asus\AppData\Local\Temp\ipykernel_3548\649135622.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Job Title'] = df['Job Title'].map(freq)

       Age  Gender Education Level  Job Title  Years of Experience    Salary
0     32.0    Male      Bachelor's        518                  5.0   90000.0
1     28.0  Female        Master's        363                  3.0   65000.0
2     45.0    Male             PhD          2                 15.0  150000.0
3     36.0  Female      Bachelor's         70                  7.0   60000.0
4     52.0    Male        Master's          1                 20.0  200000.0
...    ...     ...             ...        ...                  ...       ...
6699  49.0  Female             PhD         88                 20.0  200000.0
6700  32.0    Male     High School         70                  3.0   50000.0
6701  30.0  Female      Bachelor's        134                  4.0   55000.0
6702  46.0    Male        Master's        255                 14.0  140000.0
6703  26.0  Female     High School         38                  1.0   35000.0

[6698 rows x 6 columns]

In [286]:
numerical = ['Age', 'Years of Experience']

In [287]:
X = df.drop('Salary', axis=1)
Y = df['Salary']

In [288]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, Y, random_state=42, test_size=0.2)

In [289]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsRegressor

In [290]:
preprocessor = ColumnTransformer([
    ('scaler', StandardScaler(), numerical),
    ('onehot', OneHotEncoder(drop='first'), ['Gender',]),
    ('ordinal', OrdinalEncoder(),['Education Level',])
])

In [291]:
model = KNeighborsRegressor(n_neighbors=10)

In [292]:
regressor = Pipeline([
    ('preprocessing', preprocessor),
    ('model', model)
])

In [293]:
regressor.fit(x_train,y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('scaler', StandardScaler(),
                                                  ['Age',
                                                   'Years of Experience']),
                                                 ('onehot',
                                                  OneHotEncoder(drop='first'),
                                                  ['Gender']),
                                                 ('ordinal', OrdinalEncoder(),
                                                  ['Education Level'])])),
                ('model', KNeighborsRegressor(n_neighbors=10))])

In [294]:
regressor.score(x_test,y_test)

0.9005969109118802