In [253]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [254]:
from sklearn.datasets import load_breast_cancer
df = load_breast_cancer()

In [255]:
df.DESCR

'.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 569\n\n:Number of Attributes: 30 numeric, predictive attributes and the class\n\n:Attribute Information:\n    - radius (mean of distances from center to points on the perimeter)\n    - texture (standard deviation of gray-scale values)\n    - perimeter\n    - area\n    - smoothness (local variation in radius lengths)\n    - compactness (perimeter^2 / area - 1.0)\n    - concavity (severity of concave portions of the contour)\n    - concave points (number of concave portions of the contour)\n    - symmetry\n    - fractal dimension ("coastline approximation" - 1)\n\n    The mean, standard error, and "worst" or largest (mean of the three\n    worst/largest values) of these features were computed for each image,\n    resulting in 30 features.  For instance, field 0 is Mean Radius, field\n    10 is Radius SE, field 20 is Worst Radius.\n\n    - class:\n            - WDBC-Malignant\n            - WDBC-Benign\n\n:Summary Statistics:\n\n===================================== ====== ======\n                                        Min    Max\n===================================== ====== ======\nradius (mean):                        6.981  28.11\ntexture (mean):                       9.71   39.28\nperimeter (mean):                     43.79  188.5\narea (mean):                          143.5  2501.0\nsmoothness (mean):                    0.053  0.163\ncompactness (mean):                   0.019  0.345\nconcavity (mean):                     0.0    0.427\nconcave points (mean):                0.0    0.201\nsymmetry (mean):                      0.106  0.304\nfractal dimension (mean):             0.05   0.097\nradius (standard error):              0.112  2.873\ntexture (standard error):             0.36   4.885\nperimeter (standard error):           0.757  21.98\narea (standard error):                6.802  542.2\nsmoothness (standard error):          0.002  0.031\ncompactness (standard error):         0.002  0.135\nconcavity (standard error):           0.0    0.396\nconcave points (standard error):      0.0    0.053\nsymmetry (standard error):            0.008  0.079\nfractal dimension (standard error):   0.001  0.03\nradius (worst):                       7.93   36.04\ntexture (worst):                      12.02  49.54\nperimeter (worst):                    50.41  251.2\narea (worst):                         185.2  4254.0\nsmoothness (worst):                   0.071  0.223\ncompactness (worst):                  0.027  1.058\nconcavity (worst):                    0.0    1.252\nconcave points (worst):               0.0    0.291\nsymmetry (worst):                     0.156  0.664\nfractal dimension (worst):            0.055  0.208\n===================================== ====== ======\n\n:Missing Attribute Values: None\n\n:Class Distribution: 212 - Malignant, 357 - Benign\n\n:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n:Donor: Nick Street\n\n:Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. dropdown:: References\n\n  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction\n    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on\n    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n    San Jose, CA, 1993.\n  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and\n    prognosis via linear programming. Operations Research, 43(4), pages 570-577,\n    July-August 1995.\n  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)\n    163-171.\n'

In [256]:
x = df.data
y = df.target

In [257]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42, test_size=0.2)

In [258]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [259]:
train_sc = scaler.fit_transform(x_train)
test_sc = scaler.transform(x_test)

In [260]:
from sklearn.svm import SVC
model = SVC(kernel='rbf', C=1.0, gamma='scale')

In [261]:
model.fit(train_sc, y_train)

SVC()

In [262]:
pred = model.predict(test_sc)

In [263]:
from sklearn.metrics import classification_report, accuracy_score

print(accuracy_score(y_test, pred))

0.9824561403508771

In [264]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      0.95      0.98        43
           1       0.97      1.00      0.99        71

    accuracy                           0.98       114
   macro avg       0.99      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114

In [265]:
df1 = pd.read_csv('Salary_Data.csv')
df1

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [266]:
df1.isnull().sum()

Age                    2
Gender                 2
Education Level        3
Job Title              2
Years of Experience    3
Salary                 5
dtype: int64

In [267]:
df1.dropna(inplace=True)

In [268]:
df1.isnull().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [269]:
df1['Education Level'].unique()

array(["Bachelor's", "Master's", 'PhD', "Bachelor's Degree",
       "Master's Degree", 'High School', 'phD'], dtype=object)

In [270]:
df1['Education Level'] = df1['Education Level'].map({"Bachelor's":1, "Master's":2, 'PhD':3, "Bachelor's Degree":1,
       "Master's Degree":2, 'High School':0, 'phD':3})

In [271]:
df1

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,1,Software Engineer,5.0,90000.0
1,28.0,Female,2,Data Analyst,3.0,65000.0
2,45.0,Male,3,Senior Manager,15.0,150000.0
3,36.0,Female,1,Sales Associate,7.0,60000.0
4,52.0,Male,2,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,3,Director of Marketing,20.0,200000.0
6700,32.0,Male,0,Sales Associate,3.0,50000.0
6701,30.0,Female,1,Financial Manager,4.0,55000.0
6702,46.0,Male,2,Marketing Manager,14.0,140000.0
6703,26.0,Female,0,Sales Executive,1.0,35000.0

In [272]:
df1['Gender'].unique()

array(['Male', 'Female', 'Other'], dtype=object)

In [273]:
df1['Gender'] = df1['Gender'].map({'Male':1, 'Female':0, 'Other':2})

In [274]:
X = df1.drop(columns=['Salary'], axis=1)
Y = df1['Salary']

In [275]:
numerical = ['Age', 'Years of Experience']
category = ['Gender', 'Job Title', 'Education Level']

In [276]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, random_state=42, test_size=0.2)

In [277]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

scaler = StandardScaler()
onehot = OneHotEncoder(drop='first', handle_unknown='ignore')

In [278]:
from sklearn.pipeline import Pipeline

preprocessor = ColumnTransformer([
    ('num', scaler, numerical),
    ('cat', onehot, category)
])

In [279]:
from sklearn.svm import SVR
model = SVR(kernel='rbf',C=10000.0)

In [280]:
clf = Pipeline([
    ('preprocessing', preprocessor),
    ('model', model)
])

In [281]:
clf.fit(x_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Age',
                                                   'Years of Experience']),
                                                 ('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  ['Gender', 'Job Title',
                                                   'Education Level'])])),
                ('model', SVR(C=10000.0))])

In [282]:
pred = clf.predict(x_test)
3

c:\Users\Asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_encoders.py:242: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

3

In [283]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_percentage_error

print(mean_squared_error(y_test, pred))

189895570.05522498

In [284]:
print(r2_score(y_test, pred))

0.9334040736681114

In [285]:
print(mean_absolute_percentage_error(y_test, pred))

0.1448002703129312