In [15]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv('Housing.csv')
df

,price,area,bedrooms,bathrooms,mainroad,guestroom,basement,airconditioning,parking,furnishingstatus
0,13300000,7420,4,2,yes,no,no,yes,2,furnished
1,12250000,8960,4,4,yes,no,no,yes,3,furnished
2,12250000,9960,3,2,yes,no,yes,no,2,semi-furnished
3,12215000,7500,4,2,yes,no,yes,yes,3,furnished
4,11410000,7420,4,1,yes,yes,yes,yes,2,furnished
...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,yes,no,yes,no,2,unfurnished
541,1767150,2400,3,1,no,no,no,no,0,semi-furnished
542,1750000,3620,2,1,yes,no,no,no,0,unfurnished
543,1750000,2910,3,1,no,no,no,no,0,furnished
544,1750000,3850,3,1,yes,no,no,no,0,unfurnished

In [17]:
df['mainroad'].value_counts()

mainroad
yes    468
no      77
Name: count, dtype: int64

In [18]:

df['furnishingstatus'].value_counts()

furnishingstatus
semi-furnished    227
unfurnished       178
furnished         140
Name: count, dtype: int64

ONE-HOT Encoding by pandas

In [19]:
pd.get_dummies(df, columns=['mainroad', 'guestroom', 'basement', 'airconditioning', 'furnishingstatus'], dtype=int)

,price,area,bedrooms,bathrooms,parking,mainroad_no,mainroad_yes,guestroom_no,guestroom_yes,basement_no,basement_yes,airconditioning_no,airconditioning_yes,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,2,0,1,1,0,1,0,0,1,1,0,0
1,12250000,8960,4,4,3,0,1,1,0,1,0,0,1,1,0,0
2,12250000,9960,3,2,2,0,1,1,0,0,1,1,0,0,1,0
3,12215000,7500,4,2,3,0,1,1,0,0,1,0,1,1,0,0
4,11410000,7420,4,1,2,0,1,0,1,0,1,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,2,0,1,1,0,0,1,1,0,0,0,1
541,1767150,2400,3,1,0,1,0,1,0,1,0,1,0,0,1,0
542,1750000,3620,2,1,0,0,1,1,0,1,0,1,0,0,0,1
543,1750000,2910,3,1,0,1,0,1,0,1,0,1,0,1,0,0
544,1750000,3850,3,1,0,0,1,1,0,1,0,1,0,0,0,1

In [20]:
# with k-1 columns
df1 = pd.get_dummies(df, columns=['mainroad', 'guestroom', 'basement', 'airconditioning', 'furnishingstatus'],drop_first=True ,dtype=int)
df1

,price,area,bedrooms,bathrooms,parking,mainroad_yes,guestroom_yes,basement_yes,airconditioning_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,2,1,0,0,1,0,0
1,12250000,8960,4,4,3,1,0,0,1,0,0
2,12250000,9960,3,2,2,1,0,1,0,1,0
3,12215000,7500,4,2,3,1,0,1,1,0,0
4,11410000,7420,4,1,2,1,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,2,1,0,1,0,0,1
541,1767150,2400,3,1,0,0,0,0,0,1,0
542,1750000,3620,2,1,0,1,0,0,0,0,1
543,1750000,2910,3,1,0,0,0,0,0,0,0
544,1750000,3850,3,1,0,1,0,0,0,0,1

ONE-HOT Encoding by OneHotEncoder

In [42]:
X = df.drop('price', axis=1)
Y = df['price']
X

,area,bedrooms,bathrooms,mainroad,guestroom,basement,airconditioning,parking,furnishingstatus
0,7420,4,2,yes,no,no,yes,2,furnished
1,8960,4,4,yes,no,no,yes,3,furnished
2,9960,3,2,yes,no,yes,no,2,semi-furnished
3,7500,4,2,yes,no,yes,yes,3,furnished
4,7420,4,1,yes,yes,yes,yes,2,furnished
...,...,...,...,...,...,...,...,...,...
540,3000,2,1,yes,no,yes,no,2,unfurnished
541,2400,3,1,no,no,no,no,0,semi-furnished
542,3620,2,1,yes,no,no,no,0,unfurnished
543,2910,3,1,no,no,no,no,0,furnished
544,3850,3,1,yes,no,no,no,0,unfurnished

In [43]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False, drop='first')
X_transformed = ohe.fit_transform(X[['mainroad', 'guestroom', 'basement', 'airconditioning', 'furnishingstatus']])
X_transformed

array([[1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 1., 0.],
       ...,
       [1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1.]])

In [44]:
X_new = np.hstack((X_transformed,X[['area', 'bedrooms', 'bathrooms', 'parking']]))
X_new.shape

(545, 10)

Column Transform

In [45]:
from sklearn.compose import ColumnTransformer
cate_cols = X.select_dtypes(include='object').columns.tolist()
cate_cols

['mainroad', 'guestroom', 'basement', 'airconditioning', 'furnishingstatus']

In [46]:
preprocessor = ColumnTransformer(transformers=[('cat',OneHotEncoder(drop='first'), cate_cols)], remainder='passthrough')

In [47]:
X_new_new = preprocessor.fit_transform(X)
X_new_new.shape

(545, 10)

In [50]:
preprocessor

c:\Users\Asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\compose\_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

ColumnTransformer(remainder='passthrough',
                  transformers=[('cat', OneHotEncoder(drop='first'),
                                 ['mainroad', 'guestroom', 'basement',
                                  'airconditioning', 'furnishingstatus'])])

PIPELINE

In [51]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

In [53]:
pipeline = Pipeline(steps = [
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])
pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(drop='first'),
                                                  ['mainroad', 'guestroom',
                                                   'basement',
                                                   'airconditioning',
                                                   'furnishingstatus'])])),
                ('regressor', LinearRegression())])

In [58]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,Y, random_state=42, test_size=0.2)
x_train.shape

(436, 9)

In [59]:
pipeline.fit(x_train,y_train)

c:\Users\Asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\compose\_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(drop='first'),
                                                  ['mainroad', 'guestroom',
                                                   'basement',
                                                   'airconditioning',
                                                   'furnishingstatus'])])),
                ('regressor', LinearRegression())])

In [60]:
pipeline.score(x_test,y_test)

0.5821086947002576